import fs from "node:fs";
import path from "node:path";
import * as yaml from "js-yaml";

import {
  buildGuideIndex,
  parseModelGuideFromMetadata,
  type ModelGuide,
  type ModelGuideSource,
} from "../lib/model-guides";

export function collectModelKeys(modelsDir: string): Set<string> {
  const keys = new Set<string>();
  if (!fs.existsSync(modelsDir)) return keys;
  for (const entry of fs.readdirSync(modelsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const configPath = path.join(modelsDir, entry.name, "config.yaml");
    if (!fs.existsSync(configPath)) continue;
    const parsed = yaml.load(fs.readFileSync(configPath, "utf8"));
    const key =
      typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)
        ? (parsed as Record<string, unknown>).model
        : null;
    if (typeof key === "object" && key !== null && !Array.isArray(key)) {
      const value = (key as Record<string, unknown>).key;
      if (typeof value === "string" && value.trim()) keys.add(value.trim());
    }
  }
  return keys;
}

export function collectModelGuides(
  dataDir: string,
  knownModelKeys?: ReadonlySet<string>,
): ModelGuideSource[] {
  if (!fs.existsSync(dataDir)) return [];
  const files: string[] = [];
  const visit = (directory: string) => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(entryPath);
      else if (entry.isFile() && entry.name.endsWith(".md"))
        files.push(entryPath);
    }
  };
  visit(dataDir);
  const guides = files
    .sort((a, b) => {
      const left = path.relative(dataDir, a);
      const right = path.relative(dataDir, b);
      return left < right ? -1 : left > right ? 1 : 0;
    })
    .map((sourcePath) => {
      const source = fs.readFileSync(sourcePath, "utf8");
      const match = source.match(
        /^\uFEFF?---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)([\s\S]*)$/,
      );
      if (!match) throw new Error(`${sourcePath}: missing YAML frontmatter`);
      const metadata = yaml.load(match[1]);
      return parseModelGuideFromMetadata(
        metadata,
        match[2].replace(/^\r?\n/, ""),
        sourcePath,
      );
    });
  if (knownModelKeys) {
    for (const guide of guides) {
      if (!knownModelKeys.has(guide.modelKey)) {
        throw new Error(
          `${guide.sourcePath}: unknown model_key '${guide.modelKey}'`,
        );
      }
    }
  }
  return guides;
}

export function renderModelGuideModule(
  guides: readonly ModelGuideSource[],
): string {
  buildGuideIndex(guides);
  const publishedGuides: ModelGuide[] = guides
    .filter((guide) => !guide.draft)
    .map((guide) => ({
      modelKey: guide.modelKey,
      locale: guide.locale,
      title: guide.title,
      content: guide.content,
      sourcePath: guide.sourcePath,
    }));
  const index = buildGuideIndex(publishedGuides);
  const entries = Object.values(index).flatMap((model) => Object.values(model));
  return `import "server-only";\nimport type { ModelGuide } from "../model-guides";\n\n// Generated by loaders/model-guide-data-builder.ts\nexport const modelGuides: readonly ModelGuide[] = ${JSON.stringify(entries)};\n`;
}

export function buildModelGuideModule(repoRoot: string): string {
  const dataDir = path.join(repoRoot, "data", "model-guides");
  const outputPath = path.join(repoRoot, "lib", "generated", "model-guides.ts");
  const guides = collectModelGuides(
    dataDir,
    collectModelKeys(path.join(repoRoot, "data", "models")),
  ).map((guide) => ({
    ...guide,
    sourcePath: path
      .relative(repoRoot, guide.sourcePath)
      .split(path.sep)
      .join("/"),
  }));
  const output = renderModelGuideModule(guides);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output, "utf8");
  return outputPath;
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) ===
    path.resolve(new URL(import.meta.url).pathname)
) {
  buildModelGuideModule(process.cwd());
}
